# tests/test_migration_transformer.py
import ast
from unittest.mock import mock_open, patch

import pytest
from django.test import override_settings

from postgres_schema.management.commands.makemigrations import (
    Command,
    MigrationTransformer,
)


@pytest.fixture
def transformer():
    return MigrationTransformer(operation_class="RunInTemplate")


@pytest.fixture
def sample_migration():
    return """
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(primary_key=True)),
            ],
        ),
        migrations.AddField(
            model_name='TestModel',
            name='field',
            field=models.CharField(max_length=100),
        ),
    ]
"""


def test_basic_transformation(transformer, sample_migration):
    tree = ast.parse(sample_migration)
    result = transformer.visit(tree)
    transformed = ast.unparse(result)

    assert "RunInTemplate(migrations.CreateModel" in transformed
    assert "RunInTemplate(migrations.AddField" in transformed


def test_selective_transformation():
    """Test only transforms operations for configured apps"""
    before = """
operations = [
    migrations.CreateModel(name='AppModel', fields=[]),
    migrations.RunPython(some_function)
]
    """
    after = ast.unparse(MigrationTransformer("RunInTemplate").visit(ast.parse(before)))
    assert "RunInTemplate" in after
    assert "RunPython(some_function)" in after  # Unchanged


def test_preserves_operation_order(transformer):
    """Ensures operation order remains intact after transformation"""
    ops = """
operations = [
    migrations.CreateModel(name='First', fields=[]),
    migrations.CreateModel(name='Second', fields=[]),
]
    """
    result = ast.unparse(transformer.visit(ast.parse(ops)))
    first_pos = result.find("First")
    second_pos = result.find("Second")
    assert first_pos < second_pos


# Edge cases
def test_empty_operations():
    assert (
        ast.unparse(MigrationTransformer([]).visit(ast.parse("operations = []")))
        == "operations = []"
    )


@pytest.fixture
def migration_content():
    return """
from django.db import migrations
class Migration(migrations.Migration):
   dependencies = [('tenant_app', '0001_initial')]
   operations = [migrations.CreateModel(name='TestModel', fields=[])]
"""


@pytest.fixture
def migration_content_regression():
    return "# Generated by Django 5.1.5 on 2025-01-20 14:53\n\nimport django.core.validators\nfrom django.conf import settings\nfrom django.db import migrations, models\n\n\nclass Migration(migrations.Migration):\n\n    initial = True\n\n    dependencies = [\n        migrations.swappable_dependency(settings.AUTH_USER_MODEL),\n    ]\n\n    operations = [\n        migrations.CreateModel(\n            name='Company',\n            fields=[\n                ('schema', models.CharField(help_text='The internal name of the schema.<br>May only contain lowercase letters, digits, underscores and dashes. Must start with a letter.<br>May not be changed after creation.', max_length=36, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='May only contain lowercase letters, digits, underscores and dashes. Must start with a letter.', regex='^[a-z][a-z0-9_-]*$')])),\n                ('name', models.CharField(help_text='The display name of the schema.', max_length=128, unique=True)),\n                ('is_active', models.BooleanField(default=True, help_text='Use this instead of deleting schema.')),\n                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),\n                ('users', models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL)),\n            ],\n            options={\n                'abstract': False,\n            },\n        ),\n    ]\n"


@override_settings(POSTGRES_SCHEMA_APPS=("tenant_app",))
@patch("builtins.open", new_callable=mock_open)
def test_transform_migration_apps(mock_file, migration_content):
    mock_file.return_value.__enter__.return_value.read.return_value = migration_content

    command = Command()
    command._transform_migration("fake/tenant_app/migrations/0002_test.py")

    # Verify write contains wrapped operations
    written_content = mock_file().write.call_args[0][0]
    assert "RunInTemplate(migrations.CreateModel" in written_content
    assert "from postgres_schema.operations import RunInTemplate" in written_content


@override_settings(POSTGRES_SCHEMA_APPS=("tenant_app",))
@patch("builtins.open", new_callable=mock_open)
def test_transform_migration_regression(mock_file, migration_content_regression):
    mock_file.return_value.__enter__.return_value.read.return_value = (
        migration_content_regression
    )

    command = Command()
    command._transform_migration("fake/tenant_app/migrations/0002_test.py")

    # Verify write contains wrapped operations
    written_content = mock_file().write.call_args[0][0]
    assert "RunInTemplate(migrations.CreateModel" in written_content
    assert "from postgres_schema.operations import RunInTemplate" in written_content


@override_settings(POSTGRES_SCHEMA_MODEL=("tenant_app",))
@patch("builtins.open", new_callable=mock_open)
def test_transform_migration_schema_model(mock_file, migration_content):
    mock_file.return_value.__enter__.return_value.read.return_value = migration_content

    command = Command()
    command._transform_migration("fake/tenant_app/migrations/0002_test.py")

    # Verify write contains wrapped operations
    written_content = mock_file().write.call_args[0][0]
    assert "RunInPublic(migrations.CreateModel" in written_content
    assert "from postgres_schema.operations import RunInPublic" in written_content
